version: "3.9"

services:
  app:
    build: .
    container_name: note-test
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_PORT:  ${APP_PORT}
      DB_USER:  ${DB_USER}
      DB_PASSWORD:  ${DB_PASSWORD}
      DB_NAME:  ${DB_NAME}
      DB_HOST:  ${DB_HOST}
      DB_PORT: 5432
    networks:
      - note-net

  db:
    image: postgres:15-alpine
    container_name: note-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - note-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  note-net:

volumes:
  postgres_data:
